### ISSUE TITLE
[Request] Sprint without holding key down

### ISSUE THREAD

**Issue by EternalHabit** [nipkownix/re4_tweaks#130]
As the title says, just being able to sprint without holding a key down would be really nice. And when you stop holding forward, your character will stop sprinting. Maybe make it a toggleable option as others may like it? Keyboard only option of course.

**Comment by Mister-Curious** [comment]
I was able to achieve this by using some of the methods I talked about in issue #107 but I there were some tradeoffs. Using AHK and DS4Windows does work to make a toggle for running, but one of the problems is that the game is registering the input as coming from a keyboard, and as a result of that the interaction prompts are all shown in keyboard glyphs instead of controller icons. 

Another issue is the state of the keys. If we are using DS4Windows to keep a key pressed while the toggle is on, then there are issue when going into the inventory or interacting with QTE events.

 I'd be willing to have another look at this, but it would be cool if @emoose or @nipkownix could look into how the game handles switching from keyboard to controller icons, and see if they are able to lock the displayed icons to controller even if the input is coming from a virtual keyboard (DS4Windows or AHK).

**Comment by emoose** [comment]
`cPlayer::keyConfigTypeA` seems to handle sprint key:

```C
void __thiscall cPlayer::keyConfigTypeA(_BYTE *this)
{
  char v1; // al

  LODWORD(Key.buttonsTriggered_20) &= ~KEY_180TURN;
  v1 = this[0x54A];
  if ( v1 )
    this[0x54A] = v1 - 1;
  if ( (Key.buttonsTriggered_20 & KEY_RUN) != 0 )
    this[0x54A] = 2;
  if ( (Key.buttonsOn_18 & KEY_BACK) != 0 )
  {
    if ( this[0x54A] )
      LODWORD(Key.buttonsTriggered_20) |= KEY_180TURN;
  }
}
```
Weird thing is that's using buttonsTriggered which AFAIK only shows buttons that have been pressed that frame (ie. no buttons that were held across frames), so maybe there's something else which is handing held-down KEY_RUN somewhere.

**Comment by emoose** [comment]
Looks like `pl_R1_Run` handles the check for `KEY_RUN` being held, seems to check if either KEY_FORWARD or KEY_RUN is released, and stops sprinting if so.

There's two seperate parts in there which check them, looks like one handles releasing KEY_RUN while holding KEY_FORWARD, and the other handles KEY_FORWARD being released.

Changing 0x7639F2 to jmp instead of jnz, and nopping 0x763AF1 (1.1.0) removes the KEY_RUN check from there, and seems to allow sprint to continue until KEY_FORWARD gets released, seems to work pretty well.

Not sure if that might cause any problem somewhere though, could maybe mess with cutscenes or something I guess.

**Comment by Mister-Curious** [comment]
I would be willing to test this out if you want

**Comment by nipkownix** [comment]
Nice, we can probably add an option to invert the run button's function then. (Press nothing to run, press the run button to walk)

**Comment by emoose** [comment]
> @emoose I would be willing to test this out if you want. I am on Discord now if you have a moment to chat.

Not really sure what the best way for re4_tweaks to patch it is, so don't have much that's testable with that atm, would be nice to have something that could be changed at runtime ideally.

For now you could probably just hex edit your EXE though, search for 
`83 E0 01 33 D2 0B C2 74 66`
and change it to
`83 E0 01 33 D2 0B C2 EB 66`

Then search for
`83 E0 40 33 D2 0B C2 74 17`
and change to
`83 E0 40 33 D2 0B C2 90 90`

With those it should let the run button act as a toggle instead, until you release the forward button.

Inverting the button is a nice idea too, not really sure how to do it yet though, I guess we'd also need to patch `cPlayer::keyConfig` for it to default to the `pl_R1_Run` state instead.

**Comment by EternalHabit** [comment]
> Nice, we can probably add an option to invert the run button's function then. (Press nothing to run, press the run button to walk)

I think that wouldn't work too well because of the quick turn animation.

> > @emoose I would be willing to test this out if you want. I am on Discord now if you have a moment to chat.
> 
> Not really sure what the best way for re4_tweaks to patch it is, so don't have much that's testable with that atm, would be nice to have something that could be changed at runtime ideally.
> 
> For now you could probably just hex edit your EXE though, search for `83 E0 01 33 D2 0B C2 74 66` and change it to `83 E0 01 33 D2 0B C2 EB 66`
> 
> Then search for `83 E0 40 33 D2 0B C2 74 17` and change to `83 E0 40 33 D2 0B C2 90 90`
> 
> With those it should let the run button act as a toggle instead, until you release the forward button.
> 
> Inverting the button is a nice idea too, not really sure how to do it yet though, I guess we'd also need to patch `cPlayer::keyConfig` for it to default to the `pl_R1_Run` state instead.
> 
> E: actually I think it's `pl_R1_Walk` which first detects KEY_RUN and then switches state to `pl_R1_Run`, then the run func keeps checking KEY_RUN, and resets back to `pl_R1_Walk` if not set. Maybe switching Walk/Run in the `pl_R0_Move` func table could be one way to do it, hm.

Changing those bytes in hex worked, does RE4 have any controller/keyboard checks?

**Comment by emoose** [comment]
> Changing those bytes in hex worked, does RE4 have any controller/keyboard checks?

What kinds of checks do you mean? AFAIK that patch should work with both controller + keyboard since they should both use same code, I've only tried on kb+m so far though.

**Comment by Mister-Curious** [comment]
_"... does RE4 have any controller/keyboard checks"_
Steam does have file integrity checks if you are using ONLINE mode. So your bio4.exe will be redownloaded and rewritten each time you launch the game, The only way around this is to go into OFFLINE mode and start the game,

@emoose Thanks for the array. Looking forward to testing this out. Also, do you think there might be a way to prevent the steam verification of game files? (not just with this patch , but with a heavily patched exe like mine? I have dozens and dozens of edits, along with thousands of game files that differ from the original files. It would be nice if users didn't have to go offline as they can't connect to stat servers and also risk having to reinstall if they forget to go offline (I cant tell you how many times I did this...NOT FUN).

**Comment by nipkownix** [comment]
Hmm? Steam never verified my game files without me explicitly going into the game's proprieties and telling it to verify the integrity. I wonder why that happens for you.

**Comment by Mister-Curious** [comment]
@nipkownix maybe its not the binary then, but the game files themselves. (this being said, maybe it's a simple size check. I have a heavily edited exe, but I have never changed the file size). Can I send you one room and see if Steam tries to overwrite it?

**Comment by emoose** [comment]
Yeah I've never had Steam validate unless I asked it to neither, maybe try disabling auto-updates in Steam game properties and see if that stops it.

IIRC it can also auto-validate if the steam manifest is messed up too, could maybe try replacing it with my one (for 1.1.0 only): [appmanifest_254700.zip](https://github.com/nipkownix/re4_tweaks/files/8112307/appmanifest_254700.zip)
Extract that to `C:\Program Files (x86)\Steam\steamapps\` folder (maybe backup your original first)

Maybe someone with 1.0.6 could post the appmanifest for that version too.

**Comment by Mister-Curious** [comment]
@emoose @nipkownix thank you both for your replies. I always thought that the auto-update was something I could not control. I have looked countless times in the RE4UHD game properties and only ever saw this:

![image](https://user-images.githubusercontent.com/81539091/155071265-a7936124-5940-44e6-a331-949bf2fe8171.png)

As you can see there is no option to disable updates in the game properties, only the ability to change how it is updated. If there is another option somewhere else that I overlooked please let me know. 

I tried out the `appmanifest_254700.acf` file from @nipkownix and my game launched fine with no updates, so that is good news, but I would like to ask a few questions so I understand how this works before I rely on this to keep my modded game safe from automatic replacements.

What is this file, and what does it do? Also, why did my version of the file always not work this way? 

Thanks

**Comment by emoose** [comment]
That's just the steam manifest from my RE4 install, haven't modified that at all, afaik it uses that file to track how much % of the game you've downloaded/current game version/etc, my guess is your old one might have had some problem which steam couldn't solve for some reason.

Hopefully that should stop it trying to validate for the time being, like I mentioned that's for 1.1.0 though, if Steam usually downloads 1.0.6 for you then I guess it might eventually break some time, you could probably get around that by getting appmanifest from another 1.0.6 user though.

**Comment by nipkownix** [comment]
1.0.6 manifest here:
[appmanifest_254700_106.zip](https://github.com/nipkownix/re4_tweaks/files/8116552/appmanifest_254700_106.zip)

This one has the DLC depots listed though, not sure what Steam will do if someone uses this manifest but doesn't own the DLCs. 
You can probably edit those out in a text editor or something.

**Comment by Mister-Curious** [comment]
> like I mentioned that's for 1.1.0 though
Thanks for all of this. It seems to work fine with my modified 1.0.6. I make regular backups of my binary so I should be ok. 
> 
> This one has the DLC depots listed though, not sure what Steam will do if someone uses this manifest but doesn't own the DLCs. You can probably edit those out in a text editor or something. 
Again thanks. I will probably stick with what is working for the time being.

**Comment by emoose** [comment]
Been trying to make a hook for this but some reason it's not working right...

```C
// pl_R1_Run first KEY_RUN check
		pattern = hook::pattern("83 E0 01 33 D2 0B C2 74 ? 8B C1 83 E0 40");
		struct SprintToggleHook1
		{
			void operator()(injector::reg_pack& regs)
			{
				auto zf = 1 << regs.zero_flag;
				if (cfg.bUseSprintToggle && (regs.ef & zf) != zf) // 
					regs.ef |= (1 << regs.zero_flag); // set zero-flag so jz is always taken

				// Code we overwrote
				regs.eax &= 1;
				regs.edx ^= regs.edx;
			}
		};
		injector::MakeInline<SprintToggleHook1>(pattern.count(1).get(0).get<uint32_t>(0), pattern.count(1).get(0).get<uint32_t>(5));

		// pl_R1_Run second KEY_RUN check
		pattern = hook::pattern("83 E0 40 33 D2 0B C2 74 ? 8B C1");
		struct SprintToggleHook2
		{
			void operator()(injector::reg_pack& regs)
			{
				if (cfg.bUseSprintToggle)
					regs.ef &= ~(1 << regs.zero_flag); // unset zero-flag so jz won't be taken

				// Code we overwrote
				regs.eax &= 0x40;
				regs.edx ^= regs.edx;
			}
		};
		injector::MakeInline<SprintToggleHook2>(pattern.count(1).get(0).get<uint32_t>(0), pattern.count(1).get(0).get<uint32_t>(5));
```
For some reason when `SprintToggleHook1` gets called the zf is always set, meaning the KEY_RUN check passed - but when releasing it the `SprintToggleHook1` code doesn't seem to get called anymore - even though patching the area that it hooks manually with CE or something similar to change the jz to jmp does let it work.
Since that patch is required that must mean the jz isn't being followed in some cases, but how come when it gets to the hook, zf is _always_ set, and doesn't seem to be called anymore when zf isn't set? Doesn't make sense...

**Comment by nipkownix** [comment]
This seems to work for me:

```
	// pl_R1_Run first KEY_RUN check
	pattern = hook::pattern("83 E0 01 33 D2 0B C2 74 ? 8B C1 83 E0 40"); // 7639EB
	struct SprintToggleHook1
	{
		void operator()(injector::reg_pack& regs)
		{
			regs.eax &= 1; // Code we overwrote

			if (!cfg.bUseSprintToggle)
				regs.edx ^= regs.edx;
		}
	}; injector::MakeInline<SprintToggleHook1>(pattern.count(1).get(0).get<uint32_t>(0), pattern.count(1).get(0).get<uint32_t>(5));


	// pl_R1_Run second KEY_RUN check
	pattern = hook::pattern("8B C1 83 E0 ? 33 D2 0B C2 74 ? 8B C1 83 E0 ? 0B C2 74 ? 8B CE");
	struct SprintToggleHook2
	{
		void operator()(injector::reg_pack& regs)
		{
			regs.eax = regs.ecx; // Code we overwrote

			if (!cfg.bUseSprintToggle)
				regs.eax &= 0x40;
		}
	}; injector::MakeInline<SprintToggleHook2>(pattern.count(1).get(0).get<uint32_t>(0), pattern.count(1).get(0).get<uint32_t>(5));
```

**Comment by emoose** [comment]
Ahh I forgot that the or/xor would affect zf, some reason I thought there was a check before that stuff which was setting it, now it makes sense though.

Code you posted seems to work well, I'll PR that with the UI stuff etc for it in a little bit.
