### ISSUE TITLE
[Feature request] Let Ashley suplex enemies

### ISSUE THREAD

**Issue by linkthehylian** [nipkownix/re4_tweaks#163]
### Describe the feature you'd like to see added

In the Gamecube specific release of Resident Evil 4. If you manage to stun a cultist with one of the doors resulting them in kneeling, it shows the suplex interact prompt that Leon is normally supposed to have.

https://user-images.githubusercontent.com/20933012/162860397-bcf3a591-31ff-4ab9-bdb3-9eb82e6ff733.mp4

I realize this is a bit of a silly thing to request. But it was fixed after the Gamecube release and it's no longer possible because of that and it would be cool to see it return.

Sorry if the audio is absurdly loud, I had to get footage from YouTube.

**Comment by emoose** [comment]
>it would be cool to see it return.

Agreed, restoring some of the fun glitches like this is something I've been wanting to look into. If anyone knows any others that were fixed and might be worth restoring feel free to post about it.

(eg. the glitch that lets you jump over a fence to go out-of-bounds where some unused items are, I tried taking a look at that but couldn't really find anything code related that fixed it, I guess that was probably something fixed in a data file, maybe something like a trigger volume for the `[X] Jump` prompt was resized slightly?)

In this case I think it probably is code related though, haven't found the func responsible for suplexes yet, but think that `em10ActEvtSetKick` is what shows the kick prompt, looking at what uses that there's also code which will make it call `em10ActEvtSetFS` instead, which seems to have some character-type checks around it, will have to try looking at the GC version to see if the checks around that are any different.

**Comment by emoose** [comment]
Ahh might be wrong about the chara type stuff above, type 1 is actually Ashley I think - looking at GC code the check for type 1 is actually missing there too, so maybe the thing I mentioned above is actually what was fixing the glitch 😄 

If anyone wants to try un-fixing it, you can use cheat engine to set `bio4.exe+57513` (byte) from 01 to FF (1.1.0), which should stop that chara type check from working.
(for other vers, if you check for bytes `80 B8 C8 4F 00 00 01 0F 84` and change the 01 to FF that should also work)

**Comment by linkthehylian** [comment]
@emoose I tried searching for `bio4.exe+57519` in 1.1.0 but it seems that it found nothing?
![img](https://i.imgur.com/0IR3z4G.png)

**Comment by emoose** [comment]
Oh that's an address, click the Add Address Manually button & it should let you paste it in, make sure to change type to just Byte as well.

**Comment by linkthehylian** [comment]
Thank you! @emoose 

I also just realized that they might have fixed how these enemies are damaged by the door in this specific area. I remember a while back I tried to stun them the same way and I could never get it to work. I recorded in 30 fps after trying with 60 fps to ensure that their damage reactions were similar.

https://user-images.githubusercontent.com/20933012/163349081-b95d3ee3-c30f-4f07-b37f-a750efa05b72.mp4

Notice how they don't kneel after Ashley slams the door open. I think there was more fixed here than just a simple check.

**Comment by emoose** [comment]
>I think there was more fixed here than just a simple check.

Hmm maybe, will have to try finding the code that handles stunning enemies.

The guy that made the suplex video did mention that it took a bunch of tries to make them kneel though: https://www.youtube.com/watch?v=yO34DBqLAnc

>It took a lot of tries to knock that guy down on his knees. In fact, it took so many tries, I literally killed him with the door and had to restart. Laughs were had.

**Comment by linkthehylian** [comment]
Yeah, I just spent the last thirty minutes hitting this enemy with the door and I can't get them to kneel at all. So not only did they add checks, it seems they've prevented that specific animation from playing entirely.

Would you happen to have a save file that's at Ashley's section? I'm gonna play through the Gamecube version on Dolphin and see how fast I can get them kneel.

**Comment by linkthehylian** [comment]
Sincere apologies for the delayed update (I also had to sleep haha) but I successfully got it to work on the Gamecube version via Dolphin. I had to watch another video to ensure I was doing it correctly (I apparently wasn't lol).
https://www.youtube.com/watch?v=OkO1-hoO7BM

The good news is that I actually got it to work! I noticed that when I tried to do it the same way they do it in the video, the zealots seem to backup from the door earlier than they do on Gamecube since there's a delay when Ashley slowly opens the door to full on bashing it open. For some reason it's seems to be a lot more difficult to pull off on PC, but it's very possible.

https://user-images.githubusercontent.com/20933012/163497297-39791140-6866-44a6-bd40-d8cf9dfd87ec.mp4

**Comment by emoose** [comment]
Sweet! Great to see it's working, was that with both the memory addrs changed? I'm not sure if both are needed really, might only need the first one I mentioned (`bio4.exe+57519 byte from 01 to 255`)

>It is very much patched, I really wonder why they left in Ditman but patched this lol

The way they patched it is weird, the caller to `em10ActEvtSetFS` already had code that checked which player type you're using, but they added the Ashley check inside `em10ActEvtSetFS` instead of updating that code that was already there, guess it was most likely a port team that added it, but who knows.

**Comment by emoose** [comment]
Got some patches added into re4_tweaks now, this adds a `Misc->AllowAshleySuplex` setting to the INI, however the check inside `em10ActEvtSetFS` will always be removed, instead we'll replace that check with one inside the caller `em10_R1_Dm_Small`, or if that INI option is set to true then it'll just remove the check without adding a new one.

That should allow the game to demote `[X] Suplex` to `[X] Kick` for Ashley now, just like other characters like Ada/Hunk/Wesker, instead of having no action at all.

Haven't tested myself though since I don't have any saves with Ashley... hopefully it's working fine, I've upped a build here if anyone wants to try it out:
[dinput8-ashleySuplex.zip](https://github.com/nipkownix/re4_tweaks/files/8499110/dinput8-ashleySuplex.zip)

**Comment by linkthehylian** [comment]
I downloaded the new build and enabling it works fine. I disabled it though and it still seems to show the suplex prompt?

You also said it's supposed to show `[X] Kick` for Ashley now right? It still shows `[X] Suplex`.

**Comment by emoose** [comment]
Ah must have messed up the new check I added, will take another look at it now.

**Comment by linkthehylian** [comment]
That fixed it! Disabling it properly works now, but it still shows up as `[X] Suplex` instead of `[X] Kick`.

**Comment by emoose** [comment]
Hmm, does it perform a kick when pressed though? Kinda strange that the text didn't update, not sure what'd cause that.

**Comment by linkthehylian** [comment]
Nah, she just suplexes like the glitch is intended to do. I was also testing it with keyboard, I can switch to controller and keep you updated.

**Comment by emoose** [comment]
Oh hmm, so with it enabled it's showing Suplex, but what happens when disabled? Is it just showing no text now?

**Comment by linkthehylian** [comment]
Ah sorry, I misunderstood what you meant. Suplex works fine when it's enabled. When it's disabled there's no prompt for a kick at all.

**Comment by emoose** [comment]
Darn, maybe Ashley isn't setup to allow kicks or something (the Kick func does seem to check player type for a bunch of other chars at least), I'll try taking a look at that some more later on.

**Comment by emoose** [comment]
@linkthehylian btw just noticed you mentioned at https://github.com/nipkownix/re4_tweaks/issues/163#issuecomment-1099741577

> I noticed that when I tried to do it the same way they do it in the video, the zealots seem to backup from the door (they don't on Gamecube though?) 

>I was initially just bashing the door open immediately which is probably why I wasn't able to get it working.

Does that mean on GC, you're able to just bash door immediately and it'll work? I guess some of the AI related to doors might be changed somehow (or maybe frame-timings are messing something up at 60 compared to 30), not really sure where to try looking into that atm though.

**Comment by linkthehylian** [comment]
> Does that mean on GC, you're able to just bash door immediately and it'll work?

It seems like it. If you watch the video I used when I first started this thread, you'll notice at 0:15 that the player controlling Ashley immediately bashes the door open and the zealot still has its hands on the door when bashed open. On PC, if Ashley opens the door slowly they'll back up if they're pounding on the door. I really feel like this might have been a small AI change that QLOC did but I don't know for sure.

It's also possible because of the game running at 60 fps as you said. I'm still unfortunately unsure.
