### ISSUE TITLE
[Feature request] Full Subtitle support for English

### ISSUE THREAD

**Issue by Zaphero1** [nipkownix/re4_tweaks#174]
### Describe the feature you'd like to see added

Like Killer7 on launch and Clive Barker's Undying with its fan translations up until recently, English is only partially subtitled while nonenglish languages and fanpatches get full subtitle support. This is probably out of scope, but can English be patched to be fully supported? I know the game has been fan translated at least.
https://www.pcgamingwiki.com/wiki/Resident_Evil_4_Ultimate_HD_Edition#Localizations

**Comment by NintendoFan** [comment]
As someone who is slightly hard of hearing, this would be greatly appreciated. It was disappointing to discover the subtitles option only to have it be non functional for English.

**Comment by emoose** [comment]
Not too hard to enable subs in the code, unfortunately it looks like they never bothered to actually fill the subtitle text though :/
![20220427050502_1](https://user-images.githubusercontent.com/1755499/165438437-00530301-2fd2-4747-9926-8b7363d4a0cd.jpg)
![20220427050509_1](https://user-images.githubusercontent.com/1755499/165438447-1ee333ec-fdae-4b40-bda2-c1b897d3ac21.jpg)
![20220427050519_1](https://user-images.githubusercontent.com/1755499/165438455-c4713afb-1034-4c9f-8880-5ac5ec69bd43.jpg)

Not really sure where that's stored neither, maybe in the .dct files?
If anyone is able to mod the data files with proper subs we can patch the code easily, writing all those subs is the hard bit though...

**Comment by NintendoFan** [comment]
> Not really sure where that's stored neither, maybe in the .dct files? If anyone is able to mod the data files with proper subs we can patch the code easily, writing all those subs is the hard bit though...

I own the VR version of resident evil 4 which they added subtitles for, I can play through the game again and write down each subtitles shown if necessary.

**Comment by Zaphero1** [comment]
> I own the VR version of resident evil 4 which they added (English) subtitles for, I can play through the game again and write down each subtitles shown if necessary.

Do know that some dialogue is not included in that version, so those'll probably need to be done by ear.

**Comment by linkthehylian** [comment]
> > I own the VR version of resident evil 4 which they added (English) subtitles for, I can play through the game again and write down each subtitles shown if necessary.
> 
> Do know that some dialogue is not included in that version, so those'll probably need to be done by ear.

Yeah, this is important because of some cutscenes they censored (mainly the cabin scene) due to the game being exclusive to the Quest 2 headset.

The good news is that someone made a Steam guide and included a full transcript of the game: https://steamcommunity.com/sharedfiles/filedetails/?id=892691319

**Comment by emoose** [comment]
Hmm, so tracked down the subtitle data to the MDT files stored inside the .evd/.evd.lfs of each cutscene event - I think they're encoded in something other than ASCII/Unicode though, because hex editor doesn't show any readable strings in there.

https://residentevilmodding.boards.net/thread/1294/files-unpack-script-thief1987-toolset mentions that Thief1987 once made a tool for evd files which was capable of extracting MDT (`.MDT files Unpack Pack (Sting translate language)`), but seems link is dead for that now, and some comments there say it might not have worked well anyway...

Other than that I saw SonOfPersia made a tool for .evd files too, but I think that was only for the models inside - haven't been able to get that tool to work myself (doesn't seem to take .evd path as parameter, odd)

Will try looking into it some more, seems evd is kinda like a .zip file of sorts, hopefully shouldn't be too hard to get the .mdt file itself out of it.

**Comment by emoose** [comment]
![20220513021006_1](https://user-images.githubusercontent.com/1755499/168191649-5b3d86d9-27b6-4ce8-9a66-811c55caabd1.jpg)

:smile:

Changing the subtitles is a little complicated right now though, had to hack the modded MDT into the end of the EVD file and update some offsets to point at it instead, could probably write some tools to automate it a little though.

If anyone is happy to help write replacement text for the placeholders, I can post up a modded EXE which should make them visible when playing in English, then it's just a matter of mapping placeholders -> actual text.

Maybe the subtitles for the other languages could help give us an idea of what each subtitle ID is for too - right now I've only really mapped out English character encoding though, but looks like German mostly shares the same charset at least.

**Comment by Zaphero1** [comment]
Moving comment on subtitle guidelines here. (I know that like for example the Leon vs Krauser Cutscene needs some work with its timing if possible).

If it's capable of controlling how many lines are shown and the line clearing, I'll take this opportunity to put down the Golden Rules for subtitles (taken from linked video below, more sources in its description). I assume though the parts that can be controlled are the empty frames and how much text is in each subtitle.

- Be big.
- Use a simple (nice clean sans serif) font.
- Contrast against different backgrounds.
- Be short.
- Only contain a few words at a time. eg. 37-42 characters and only 2 lines are shown on the screen at once. -
- Have text break at a natural point in the dialogue.
- Stay on screen long  enough, about 0.3 seconds per word according to BBC guidelines.
- Have a few frames of empty subtitles between each subtitle (it's a subtle flash that lets the viewer know when new subtitles pop up)
- Indicate the speaker.
- Cover all dialog.

Netflix guidelines:  https://partnerhelp.netflixstudios.com/hc/en-us/articles/215758617-Timed-Text-Style-Guide-General-Requirements
BBC guidelines: https://bbc.github.io/subtitle-guidelines/
Game Maker's Toolkit video on the topic: https://youtu.be/4NGe4dzlukc

**Comment by avalonv** [comment]
Question from a new user. I'm mildly deaf and was pointed here from a steam thread after complaining about the lack of English subs (very, very happy this exists by the way!)

Having said that, I'm still a little confused as to whether re4_tweaks is already capable of enabling full English subtitles or not, and I couldn't find information about the status of this feature on the documentation. Do I need to use this old release or nah?

https://github.com/nipkownix/re4_tweaks/pull/185#issuecomment-1133795899

**Comment by linkthehylian** [comment]
RE4 has a subtitles option found at the very bottom of the settings menu. It's grayed out and turned off by default since the game's "subtitles" are just placeholder text prior to these edits. Using the latest version of re4_tweaks re-enables the option automatically and allows you to actually turn it on.
