### ISSUE TITLE
[Feature request] Keep Leon's jacket after rescuing Luis

### ISSUE THREAD

**Issue by linkthehylian** [nipkownix/re4_tweaks#191]
### Describe the feature you'd like to see added

I have a lot of friends that are disappointed that Leon doesn't keep his jacket after rescuing Luis even when doing NG+. It would be cool to have the option to see him keep his jacket so that you're able to see him wear it for the entirety of the game and not for just the first part.

**Comment by LethalPlacebo** [comment]
+1 to this. I know it's possible via cheat engine, but having it just be an easy tickbox in this mod would be great.

**Comment by FutonGama** [comment]
+1

**Comment by emoose** [comment]
Anyone know a CE trainer that implements this? I'm not really sure how to do it while keeping cloth anims etc working on the jacket, unless the trainer is just swapping out the EmXX model entirely for Em00 or something.

**Comment by linkthehylian** [comment]
> Anyone know a CE trainer that implements this? I'm not really sure how to do it while keeping cloth anims etc working on the jacket, unless the trainer is just swapping out the EmXX model entirely for Em00 or something.

It looks like [Fluffy's Mod Manager 5000](https://fluffyquack.com/tools/modmanager.zip) has a built-in trainer implements the option to do this. But I tried it and it doesn't seem to work? I'm guessing because of the patched executable, that or it's incompatible with the HD Project.

**Comment by emoose** [comment]
@linkthehylian ah whoops forgot to check game language before applying english subtitle patch - as a workaround you can remove the custom .mdt files and it should skip trying to patch it, I'll add a check for it soon.

**Comment by RiasatSalminSami** [comment]
> Anyone know a CE trainer that implements this? I'm not really sure how to do it while keeping cloth anims etc working on the jacket, unless the trainer is just swapping out the EmXX model entirely for Em00 or something.


Currently you can keep the jacket if you used bug menu and skip past the section where Leon gets knocked out by Big Cheese [followed by the Leon & Luis tied up cutscene]. Then Leon gets to keep his jacket throughout rest of the game.

The jacket physics seems to work just fine during cutscenes. There really isn't that many glitches that I've seen with his jacket. It's basically functional.

Screenshots: https://cdn.discordapp.com/attachments/288942291677216768/952672246416158823/unknown.png

**Comment by nipkownix** [comment]
Ah, I see. I distinctly remember seeing Leon's jacket going through his body in some cutscene, but maybe it was a fluke or something.

I'll be adding this as part of a costume "customization" thing I'm working on. Nothing too crazy, but we'll be able to combine Special 1/2/3 costumes, including keeping the jacket.

**Comment by nipkownix** [comment]
Here's a test build with 1833d8eea1971335f13962abe9:
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/8792468/dinput8.zip)

Seems to work just fine. Only problem I've noticed is the game crashing in one specific condition: If you're playing as Ashley in her castle section, the game crashes if you try to switch from her "normal" or "popstar" outfits to her "armor" one. Not sure what's going on there. Maybe @emoose could take a look? I'm tempted to just not applying the costume changes for that section to avoid the crash.

**Comment by linkthehylian** [comment]
I just tested the new dll and I don't seem to have that issue? I started a new game with Special 1 (RPD & Popstar outfits) and did the override to force her Armor outfit, got to her section and everything seemed to be fine. I did also notice that the "Clank Clank" noise was back despite having the silence option for it enabled. 😄

**Comment by LethalPlacebo** [comment]
Testing out the new build, and after saving Luis, the jacket works perfectly in gameplay, but in every cutscene from the capture scene and onward, the lower half of Leon's jacket was just missing. Here's a couple screenshots:

https://imgur.com/a/uGlTAq7

This really isn't a big deal for me since it works just fine in gameplay and that's what I wanted it for. The cutscenes prior to being capture all work perfectly fine. Just figured that people might wanna know anyway.

**Comment by nipkownix** [comment]
> I just tested the new dll and I don't seem to have that issue? 

Oh? That's weird. Are you using the HD project? I'm testing without it, that could be why you're not crashing. Hmm.

>I did also notice that the "Clank Clank" noise was back despite having the silence option for it enabled. 😄

Oof, really? Can't imagine what's the issue there. I'll take a look :p

> but in every cutscene from the capture scene and onward, the lower half of Leon's jacket was just missing.

Just tested those scenes by area jumping to them and the jacket is normal for me. Maybe the game sets some flag when you get to the capture scene itself, and that messes with the jacket? I'll look into it. Thanks for testing!

**Comment by nipkownix** [comment]
@LethalPlacebo, can you test if the jacket is fine with this build?
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/8793756/dinput8.zip)

**Comment by linkthehylian** [comment]
Noticed something else (using the build from https://github.com/nipkownix/re4_tweaks/issues/191#issuecomment-1140481505), if the override option is set to force Ashley's armor outfit. The game will force the Chicago Typewriter barrel model that's only used for the Mafia outfit. You can even perform the unique reload animation and everything.

It looks like Ashley's model is also being checked and sets it for Leon anyway regardless of his outfit?

![254700_20220529123540_1](https://user-images.githubusercontent.com/20933012/170881184-f7ff0d6a-9049-43c7-8d24-4218b79192ef.png)
![254700_20220529123554_1](https://user-images.githubusercontent.com/20933012/170881193-290c2773-92c8-42e7-917c-499e1bde3a19.png)

**Comment by nipkownix** [comment]
> It looks like Ashley's model is also being checked and sets it for Leon anyway regardless of his outfit?

Huh, you're right, there's another armored Ashley check at ``wep11_r2_reload``. I wonder why they did it this way.
There seems to be a bunch of other armor check too. I'll check if these are important or not.

**Comment by nipkownix** [comment]
> The game will force the Chicago Typewriter barrel model that's only used for the Mafia outfit. You can even perform the unique reload animation and everything.
> It looks like Ashley's model is also being checked and sets it for Leon anyway regardless of his outfit?

Looks like you're right. I've pushed some changes that should fix this issue, and also contains the ``PlClothSetLeon`` fix I mentioned earlier.

I've also updated SilenceArmoredAshley. You should now be able to enable/disable it on the fly. Let me know if you're free from the clanking again :p

Test build:

[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/8794025/dinput8.zip)

**Comment by linkthehylian** [comment]
> I've also updated SilenceArmoredAshley. You should now be able to enable/disable it on the fly. Let me know if you're free from the clanking again :p

That's fixed! But it looks like the Chicago Typewriter barrel model is still being forced unfortunately.
![254700_20220529153310_1](https://user-images.githubusercontent.com/20933012/170888421-7216b6de-8fb1-44ed-bc57-79c9e13447b2.png)

**Comment by nipkownix** [comment]
Hmm, what about the reload animation?

**Comment by linkthehylian** [comment]
> Hmm, what about the reload animation?

Yep, can confirm that it's still there as well.

**Comment by nipkownix** [comment]
Weird, it seems to be working just fine on my end:

![image](https://user-images.githubusercontent.com/33870163/170888624-2d6edfd6-90a5-479f-a592-0924d6bc44f0.png)

**Comment by linkthehylian** [comment]
Yeah, it's only when you override the Armor outfit. Just tested both Normal and Popstar and it shows the correct model for the Chicago Typewriter. I'm thinking it might be something with the HD Project then.

**Comment by nipkownix** [comment]
You're using RPD Leon and Armor Ashley, right? I was getting the exact same issue before the changes in e0f20f098e1007c776. Not sure why that hasn't fixed it for you too. Hmm..

**Comment by linkthehylian** [comment]
Correct, I'm using the latest build from https://github.com/nipkownix/re4_tweaks/issues/191#issuecomment-1140503367 as well assuming that's the latest one.

Absolutely! Here it is.
[savegame00.zip](https://github.com/nipkownix/re4_tweaks/files/8794176/savegame00.zip)

**Comment by nipkownix** [comment]
> Correct, I'm using the latest build from https://github.com/nipkownix/re4_tweaks/issues/191#issuecomment-1140503367 as well assuming that's the latest one.

Yeah, that's the latest one.

> Absolutely! Here it is.
Thank you!
So, I just loaded save number 11 and had no problems there either. Weird.
Something in your game is definitely still making the wrong check, though. I'll keep digging.

**Comment by LethalPlacebo** [comment]
> @LethalPlacebo, can you test if the jacket is fine with this build? [dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/8793756/dinput8.zip)

@nipkownix Hey just got around to testing this version. It is worth noting that I am using the HD Project, sorry for not clarifying that sooner. Anyway, using the build you told me to use in the comment and it works! The lower half of the jacket no longer disappears!

https://imgur.com/a/dsgnhnZ

I dunno if it'll help, but you're right that in the previous version Ashley's costume was set to armor, but I forgot to test changing it before testing out the new version. In the new version, her costume was still set to armor, but the jacket still worked fine.

Last thing I have to say is that when Leon's costume is set to the "normal" setting, at the beginning of the game he does not have the jacket, but I assume that this is intentional.

**Comment by linkthehylian** [comment]
@nipkownix False alarm, I somehow didn't realize that I was still using the build from https://github.com/nipkownix/re4_tweaks/issues/191#issuecomment-1140481505. It's fixed. 😄 
![254700_20220530035130_1](https://user-images.githubusercontent.com/20933012/170944279-e486d47b-c40b-4e63-a109-814a73cad79a.png)

**Comment by nipkownix** [comment]
> Anyway, using the build you told me to use in the comment and it works! The lower half of the jacket no longer disappears!

Nice! Thank you for testing.

> Last thing I have to say is that when Leon's costume is set to the "normal" setting, at the beginning of the game he does not have the jacket, but I assume that this is intentional.

Yeah, that is intentional. I called Leon without a jacket the "normal" costume because that's what he looks like for most of the game. Besides, "Leon w/o the Jacket" would be too much to write in the ini file :p

>  False alarm, I somehow didn't realize that I was still using the build from https://github.com/nipkownix/re4_tweaks/issues/191#issuecomment-1140481505. It's fixed. 😄

Ah, cool! There are still some costume checks inside that function, though:

![image](https://user-images.githubusercontent.com/33870163/171000222-2d0b12dc-70f6-4dcd-8444-a496c9ea030b.png)

I wonder if it is worth it to patch those too. Hmm.

**Comment by laymonage** [comment]
This is a bit off-topic, but now I'm wondering: is it possible to make Ashley invincible (and can't be picked by enemies) just like with the armor suit, but with the other costumes as well? I'm guessing the logic might be tightly coupled to the armor suit, but since you're patching those costume checks, maybe it's possible to do this...

**Comment by linkthehylian** [comment]
Noticed another issue, I'm not entirely sure what Leon's outfit is doing here? I'm using the override RPD and Armor outfits if someone wants to attempt to reproduce this. Interesting how the Armor outfit doesn't show in the cutscenes either.
![254700_20220603164142_1](https://user-images.githubusercontent.com/20933012/171950984-f6374544-3733-41b6-a53d-9553221ca14a.png)
![254700_20220603165132_1](https://user-images.githubusercontent.com/20933012/171951005-5ffcd8d9-a999-4a31-8f66-b66bfe619083.png)

**Comment by MetalGearAlex1** [comment]
> >

Hello. I wanted to ask. Can u or albert or emoose upload a  closer to 1.1 release test version build please? Im very excited but am afeared now that albert is busy with 3D school he wont be able to finish the polishing of the game with ur greatly appreciated & needed tweaks. Also with the new RE4 trailer, this is a prime time to REALLY get on the re4 fan bandwagon hype with alberts hd work he worked so hard on for 8 years. May God bless him and u and emoose. I was here since the beginning when all this started and still here waiting for 1.1 and also i helped with green screen issue early on. Plz respond. Thanku. I am indebted to u all and re4islife. I will donate more later.

**Comment by emoose** [comment]
Also ran into same issue @linkthehylian posted:

![20220611071129_1](https://user-images.githubusercontent.com/1755499/173207228-51936bb9-d88c-4206-8760-db78004a66a9.jpg)

I don't remember exactly what clothing overrides I used though, but seems this only happened during cutscenes, gameplay would show it fine.

**Comment by nipkownix** [comment]
Yeah, seems the game is trying to give Leon a jacket even if you're not using the jacket costume. Haven't looked into it yet, though.

**Comment by nipkownix** [comment]
Fix is up. Same problem as before. Meh.

Build here:
https://github.com/nipkownix/re4_tweaks/suites/6894320470/artifacts/267321410

**Comment by nipkownix** [comment]
Hmm, the fix above "fixed" Leon, but messes up Ashley:

![image](https://user-images.githubusercontent.com/33870163/173713406-ff5d233b-e0d2-4953-88bd-afd4b044bfc3.png)

Not really sure what the problem is. 

@emoose, if you want to take a look, this is handled by ``Event::ExePacket_SetParts``.
For now, I'll just remove the fix mentioned above. People who use the costume overrides will just have to deal with possible funny business in cutscenes, I guess.
