### ISSUE TITLE
Quick weapons switch 

### ISSUE THREAD

**Issue by Taitass** [nipkownix/re4_tweaks#195]
### Describe the feature you'd like to see added

The ability to switch weapons with single press of a button without going to inventory menu.

**Comment by emoose** [comment]
Looks like it can be done by overwriting `ItemMgr+0x10` (uint16) with the weapon ID (0xc70fe4 in 1.1.0), then calling `WeaponChange`, I've only tested it with a hook in the main game thread though, not sure if it'd work outside of it.

Only noticed one issue, the inventory still has your original weapon equipped, guess they store the equipped flag for the inventory items separately, probably because they can be moved around etc.
