### ISSUE TITLE
Make the module base address unchanged

### ISSUE THREAD

**Issue by qingsheng8848** [nipkownix/re4_tweaks#201]
### Describe the feature you'd like to see added

![5 F80H3X((4KPQ6TZK39$~B](https://user-images.githubusercontent.com/98869895/172580905-03503f29-d66d-491d-a7ce-9c9fb0e63e86.png)
When we restart the computer, or modify the bio4.EXE file.  The module base address of the game will change. As shown in the figure.  This limits our modifications to the game EXE file.  Is there any way to fix it?

**Comment by qingsheng8848** [comment]
In the 2007 version it worked without any issues.  We can freely modify EXE files.  But not in 2014 version

**Comment by emoose** [comment]
If you set the relocations stripped flag it should stop Windows from relocating it, making it stay at 0x400000

![image](https://user-images.githubusercontent.com/1755499/172670600-1611515f-e889-425f-8671-cbe1e5c02824.png)

**Comment by qingsheng8848** [comment]
> 您可以设置 relocations stripped 标志，该标志应该阻止 Windows 重新定位它，使其保持在 0x400000：（ 这在使用 IDA 调试时非常有用，否则 IDA 每次调试时都会花费 5 分钟以上重新定位 >.>）
> 
> ![图片](https://user-images.githubusercontent.com/1755499/172670600-1611515f-e889-425f-8671-cbe1e5c02824.png)

Ahhh, thank you very much for your answer

**Comment by emoose** [comment]
Did you show your friend the post I sent before? That flag & the .reloc edit should work pretty much the same, both should make EXE use the default base addr (0x400000 for RE4) instead of moving it around.

Anything dynamically allocated (like pointers to certain things in memory) would still be placed at random addresses though (.reloc wouldn't affect that neither afaik) - but things that are actually inside the EXE file on your HDD should get put at a static offset.

re4_tweaks should work fine with either method, don't know about other mods though - IIRC companion will complain about game not being 4GB patched if you use this flag though even if the 4GB patch is present, since this flag & 4GB patch both change the same byte.

There is another flag you can set which might work better with companion (OptionalHeader -> DllCharacteristics -> uncheck "DLL can move"), haven't tested that with companion yet but seems to make addr static like the other flag, but if companion still gives a warning with both of them maybe editing .reloc would be better.

Here's a zip with both flags, bio4_flag1 sets the first flag I mentioned (FileHeader -> Characteristics -> "Relocation info stripped"), the bio4_flag2 sets the other one, both have 4GB patch applied too: 
[bio4-106-relocflags.zip](https://github.com/nipkownix/re4_tweaks/files/10191870/bio4-106-relocflags.zip)

**Comment by Mister-Curious** [comment]
> Here's a zip with both flags

Thanks for all this info, I am sure it will be helpful. I will let you know how things go after we decided which way to go and how it all works out. I'm relieved that it will not interfere with your work!

Peace!

**Comment by Mister-Curious** [comment]
Sorrry I know this is closed but I have some questions about nuking the table. I posted them here:

https://cs.stackexchange.com/questions/158869/questions-about-relocation-tables

**Comment by shadows-kings** [comment]
> > Here's a zip with both flags
> 
> Thanks for all this info, I am sure it will be helpful. I will let you know how things go after we decide which way to go and how it all works out. I'm relieved that it will not interfere with your work!
> 
> Peace!

Hi , I have a Question Mr.Curious , I'm working on a Resident Evil 4 project, and I encountered a problem. I installed the following functions in my bio4.exe:

**AEV CHAIN**
- REQUIRES:
AEV-FSE
AEV-ESE
AEV-AutoBlock
AEV-CAM
AEV-Checkpoint

**Sanity Checking Function / POINTER EDIT** (because I'm using the companion dll in my project)

I wanted to use the AEV-CAM modification, but it didn't work for me. I did the following:

CAM:
Create a new entry in CAM (its number is 17 and its index is 11)
Page 1:
Type 3

Page 2:
Type 8

AEV:
Create a new entry of type 2 and add Offset[128..131] = 0xCC17 and Offset[52] = 0x2 where I want Camera 17 to be hidden and appear via EVENT.

The result is that the camera's TriggerZone doesn't disappear.

Am I having a problem with the functions added to bio4.exe, or with the way I'm executing the process?

I hope you can respond. Thank you.
