### ISSUE TITLE
EnableFastMath causing issues with Plagas

### ISSUE THREAD

**Issue by nipkownix** [nipkownix/re4_tweaks#226]
@emoose Something Albert just reported: https://youtu.be/oZ5D9rqEwqU

Looks like they just become invisible for a few frames or so. 
I haven't looked into it yet, so I don't have much more info, but I do know that this specific plaga model shown in the video has its animation running at 30 fps, same thing as the rifle reload animation. Might not be related at all, but could be worth checking if the rifle also disappears when reloading.

**Comment by emoose** [comment]
Huh that is strange, will have to try figuring out which function is causing that, likely just one of them that's causing it.

Wonder if it could be related to the issue @Mister-Curious found [when hooking PSMTXAdd](https://github.com/nipkownix/re4_tweaks/pull/192#issuecomment-1144223890), maybe the problem there wasn't with the hook (which seemed like it should have been compatible anyway), but maybe the code for his hook exposed some issue with our PSMTXAdd impl or something like that... not sure yet though, will look into it more soon.

**Comment by emoose** [comment]
Hmm seems the culprit is the `PSVECMag` hook, that calls into our `SQRTF` reimpl which uses the reciprocal square root method from https://stackoverflow.com/questions/1528727/why-is-sse-scalar-sqrtx-slower-than-rsqrtx-x (`SSESqrt_Recip_Times_X`)

Changing it to a normal `sqrt` call seems to be enough to fix it, so guess that reciprocal method isn't accurate enough or something, will see if there's some better way to fix up `SQRTF`

**Comment by Mister-Curious** [comment]
Curious if this has been resolved and added to a public release? I just noticed it too!

**Comment by nipkownix** [comment]
Ah, it is fixed, but we haven't made a proper release yet.
You can get the latest build with this fix here:
https://github.com/nipkownix/re4_tweaks/suites/7258175405/artifacts/291789662

**Comment by Mister-Curious** [comment]
thank you !
