### ISSUE TITLE
Corrected the trajectory of the Krause bow

### ISSUE THREAD

**Issue by qingsheng8848** [nipkownix/re4_tweaks#252]
### Describe the feature you'd like to see added

I don't know if you have noticed that when we use Krause's bow to aim at the head of an enemy in the distance, the arrow often fails to hit the enemy's head.  I don't know how to fix it, I'm out of ideas

**Comment by linkthehylian** [comment]
I always wondered why his bow felt so off to use during gameplay. Is it possible that the red laser is slightly misaligned? Because that laser basically ensures whether you hit an enemy or not.

**Comment by nipkownix** [comment]
Hmm, I may be talking nonsense here, but I always thought they just tried to mimic some "realistic" trajectory like so:

![image](https://user-images.githubusercontent.com/33870163/178855217-7688bf4b-a240-430f-9c14-d92137e00f50.png)

Been a while since I played as Krauser though, so I'll have to check again.

**Comment by qingsheng8848** [comment]
In version 1.0.6, we can get the initial coordinates of the arrow shot in Bio4.exe + 1D3208

**Comment by qingsheng8848** [comment]
Bio4.exe + 51202a, we can get the speed of arrows here. If we change the speed to -10, we can find the arrow misplacement

**Comment by qingsheng8848** [comment]
If we can find the coordinates of the infrared sight, maybe we can fix it
