### ISSUE TITLE
[Feature Request] Knife Aiming should aim at where the player looking at instead of always facing forward

### ISSUE THREAD

**Issue by JagBone** [nipkownix/re4_tweaks#253]
### Describe the feature you'd like to see added

Whenever the player aims the knife, the aim position would always resets to face forward and then the player will need to angle back they were previously aiming at. For example, if you are aiming down with a gun and then switch to knife, Leon will face forward instead of down where you were looking at. This is just a weird issue and very annoying. With the current RE4 Tweaks, I can easily bring it back to where I was aiming but I hope to see this issue fixed.

**Comment by Mister-Curious** [comment]
This isn't really a bug, its how the game was intended to play out. What happens when you ready your knife is that an animation plays (FCV) file. That FCV controls where the player model's bones move, and the 3d mesh that is attached to those bones. Without having an FCV tool and some serious wizardry I don't think this is a realistic thing you can hope for. Sorry, but this game isn't easy to mod like that.

**Comment by nipkownix** [comment]
Found something interesting about this.

Seems the game has mostly supports doing this already, but for some reason, it goes unused, as some code needed to make it work just isn't there.

Will see if I can restore that functionality.

**Comment by nipkownix** [comment]
@emoose, I just pushed a WIP commit with some camera tweaks here: c0a061237f225dde54

This uses some leftover Wii code and some other things to make the weapon point to where your camera is pointing to, instead of pointing to the center of the screen.
Most of the weapons have code to "skip" the initial wait, fixing the problems shown in the video above. It improves the experience quite a bit IMO, but.. there are two weapons that don't have the Wii code path: grenades, and.. the knife, sadly. I tried comparing the code from the weapons that do have it, but couldn't replicate it for the grenade and knife.
If you could take a look at some point and try to figure out how to reproduce the changes, maybe we could polish this up and add it as a full feature.

**Comment by nipkownix** [comment]
Got something working:

https://user-images.githubusercontent.com/33870163/183227850-f5816447-9f16-4b3c-abeb-23caea07af8d.mp4

It works for every weapon. Ironically, the knife is the one where it "looks" the worst, lol

This is for mouse and keyboard only for now. Not sure if you're using a controller, but I expect to make it work for controllers too at some point.
