### ISSUE TITLE
Items shot down from Bird's nests ascending to sky 

### ISSUE THREAD

**Issue by Mister-Curious** [nipkownix/re4_tweaks#283]
Greetings friends! I recently noticed that after shooting a bird's nest (r11b, and in another room), that the items that are supposed to fall to the ground are actually ascending towards the sky! I removed the RE4Tweaks DLL and the problem resolved immediately. 

Here is the log file:
[xinput1_3.log](https://github.com/nipkownix/re4_tweaks/files/9162174/xinput1_3.log)

**Comment by nipkownix** [comment]
Yeah, I broke that in between releases, but fixed it when I released version 1.7.7. I see you're using a trainer PR build, though. I imagine there should be an up-to-date CI build in that PR?

**Comment by Mister-Curious** [comment]
@nipkownix thanks for chiming in. I don't keep up with all the releases that often, and am really not familiar with the lingo 'CI build' (I assume PR is Public Release)?. What is the best way for me to know when this is fixed?

 Anyways, thanks for being on top of it

**Comment by nipkownix** [comment]
Ah sorry, I assumed you were familiar with GitHub.
PR means Pull Request, which are the items you see in [this page](https://github.com/nipkownix/re4_tweaks/pulls).

'CI build' is an automated build, made by [GitHub actions](https://github.com/nipkownix/re4_tweaks/actions). Usually, when you got to a PR and click "details":
![image](https://user-images.githubusercontent.com/33870163/180337189-1cd5184d-8db4-43ea-9dae-16ea9c94c4ef.png)

You go to a page where you can click "Summary" and get the latest automated build from there. I'll admit this is a bit hidden, though. GitHub should make this stuff a bit easier to find.
The trainer PR, however, is marked as a "draft", meaning it isn't ready yet, so that's probably why there's no automated build for it.

>What is the best way for me to know when this is fixed?

Well, it is fixed already in the latest release, but if you need a W.I.P trainer build with that issue fixed, this build should work:
[dinput8-trainer_fix.zip](https://github.com/nipkownix/re4_tweaks/files/9163584/dinput8-trainer_fix.zip)

We'll update the trainer PR at some point with the latest changes, and hopefully merge it soon.

**Comment by Mister-Curious** [comment]
thank you. @nipkownix
