### ISSUE TITLE
Multiple fatal errors after updating to 1.7.7.4 or 1.7.7.5

### ISSUE THREAD

**Issue by guifisilva** [nipkownix/re4_tweaks#299]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

Initialization is interrupted by multiple error boxes. Many crashes are being dumped at once.

After reverting back to 1.7.7.3 game starts up as expected, without errors.

[bio4.exe.20220729212928.zip](https://github.com/nipkownix/re4_tweaks/files/9224044/bio4.exe.20220729212928.zip)
[bio4.exe.20220729212929.zip](https://github.com/nipkownix/re4_tweaks/files/9224045/bio4.exe.20220729212929.zip)
[bio4.exe.20220729212930.zip](https://github.com/nipkownix/re4_tweaks/files/9224047/bio4.exe.20220729212930.zip)
[bio4.exe.20220729212931.zip](https://github.com/nipkownix/re4_tweaks/files/9224048/bio4.exe.20220729212931.zip)
[bio4.exe.20220729212925.zip](https://github.com/nipkownix/re4_tweaks/files/9224050/bio4.exe.20220729212925.zip)
[bio4.exe.20220729212927.zip](https://github.com/nipkownix/re4_tweaks/files/9224051/bio4.exe.20220729212927.zip)

**Comment by nipkownix** [comment]
These errors are not fatal, actually. And they're not being caused by the game/re4_tweaks.
This is caused by me switching from ``SetUnhandledExceptionFilter`` to ``AddVectoredExceptionHandler``. ``SetUnhandledExceptionFilter`` wasn't catching every exception, while ``AddVectoredExceptionHandler`` apparently catches irrelevant ones. Very annoying. Guess the safest bet is to go back to ``SetUnhandledExceptionFilter``, and _maybe_ have ``AddVectoredExceptionHandler`` if ``VerboseLog`` is enabled if we ever need that.

In any case, just delete your CrashDumps folder, and the issue will go away.

**Comment by guifisilva** [comment]
Oh I thought something was going really wrong since I needed to load the task manager to kill the game -- it was really stuck.

But yep, after deleting the folder the game runs just fine. Nice!

Thanks again for the hard work, I really appreciate it.
