### ISSUE TITLE
RE Tweaks UI scaling for higher DPI monitors.

### ISSUE THREAD

**Issue by RiasatSalminSami** [nipkownix/re4_tweaks#334]
### Describe the feature you'd like to see added

It's already possible to increase the font size to some extent. But it's still not readable when I play the game at 4k on 22inch monitors. The texts look too tiny.  Would it be possible to add even higher values to increase the font size?

**Comment by nipkownix** [comment]
Hmm, high DPI is complicated for me since testing is a pain with my monitor, but I'm thinking we can probably simply scale the UI based on Window's current DPI setting. The UI currently has some code that doesn't account for scaling, but I've begun updating those parts to test if this is a proper solution:

[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/9585764/dinput8.zip)

Let me know if this build looks at least okay-ish at 4k.

**Comment by nipkownix** [comment]
Should be addressed now.
