### ISSUE TITLE
Add FixQTE under 60 FPS fixes

### ISSUE THREAD

**Issue by Keith94** [nipkownix/re4_tweaks#46]
Hi and thanks for the latest release :)

Just a minor nitpick/question, but would it make sense to add the `FixQTE` together with the other `60FPSFixes`? So there is only one option, and not two? Let me know what you think.

**Comment by nipkownix** [comment]
Yeah, I've been thinking about this, but I decided it is best to actually split the stuff inside `60FPSFixes` into their own options.
I've created a new "frame rate" category for those options:

![image](https://user-images.githubusercontent.com/33870163/151399454-27a8b18b-af1c-4163-807e-79dc2647b2e3.png)

The aiming speed stuff was moved to the new "controller" tab:

![image](https://user-images.githubusercontent.com/33870163/151399558-0e2085a2-6179-4417-9641-32c4b3b181b0.png)

I think this is better since it gives the users more control of what is toggled on or off.

**Comment by Keith94** [comment]
That's even better. Looks good to me. Thanks!
