### ISSUE TITLE
"Assertion failed" pls help!

### ISSUE THREAD

**Issue by Unlucermas** [nipkownix/re4_tweaks#462]
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

![image](https://user-images.githubusercontent.com/124608836/217034585-bcde01d8-5290-4cc2-b00e-fc7e0aae120d.png)
I have this error and I don't know how to fix it, help :(
I have the steam version, I'm from Argentina, I saw that this problem is recurring in the German version but I don't think that's the problem
this is my .exe if you need it [bio4.zip](https://github.com/nipkownix/re4_tweaks/files/10665429/bio4.zip)

**Comment by emoose** [comment]
Hm, seems like that's the normal 1.1.0 EXE that should be supported.

The E:\Porgrams\ path it shows is odd though, that comes from whoever built the DLL, I don't think any of the official re4tweaks DLLs use that, are you using a custom version at all?

Maybe try the version from https://github.com/nipkownix/re4_tweaks/releases/tag/1.8 and see if that works for you.

**Comment by nipkownix** [comment]
E:\Porgrams\ comes from my PC, actually :p

On older releases I used to upload the dlls that I built. 1.8 comes from GitHub actions, so that's why it is different.

Seems OP is using winmm.dll as the name of the library, though, so I'm guessing maybe that winmm.dll is from an older release, back when that was the default name. If both winmm and dinput8 are present at the same time, that would explain why winmm is faling to fine the patterns.

@Unlucermas, can you delete winmm.dll and try again?

**Comment by Unlucermas** [comment]
> E:\Porgrams\ comes from my PC, actually :p
> 
> On older releases, I used to upload the dlls that I built. 1.8 comes from GitHub actions, so that's why it is different.
> 
> Seems OP is using winmm.dll as the name of the library, though, so I'm guessing maybe that winmm.dll is from an older release, back when that was the default name. If both winmm and dinput8 are present at the same time, that would explain why winmm is faling to find the patterns.
> 
> @Unlucermas, can you delete winmm.dll and try again?


I did it and it worked! thank you
