### ISSUE TITLE
[Feature request] Option to Include/Exclude Additional Enemies in RE4 HD Project

### ISSUE THREAD

**Issue by HamilcarB** [nipkownix/re4_tweaks#536]
### Describe the feature you'd like to see added

While installing the RE4 HD Project, I observed that a Novistador enemy was added by default in one of the castle rooms (R20a - Hallway - To Gallery). This enemy was not present in the original game, as seen in this video: (https://youtu.be/keGLW-rKuzI?t=790)
I request the developers to provide an option in re4_tweaks to include or exclude any additional enemies that may have been added in the RE4 HD Project.

**Comment by Mister-Curious** [comment]
"The Novistador in the room on the way back to the broken butterfly is only there in the GameCube version of the game normally. When it was ported to other PS2 it was removed for some reason, along with a bunch of other stuff, and that version is what all later ports were based on. The RE4 HD Mod pack adds it back in because it was trying to mimic the original GameCube release as much as possible".

Here is a [download link ](https://drive.google.com/file/d/1Asw8ii9sSepajjGVI4Saz2p_G77h-tsh/view?usp=share_link)to the original emelon03.esl file for the vanilla RE4UHD. Try this one out and let me know if this resolves your issue. You will need to ensure you arent loading from a save because ESL data is stored there after each chapter end and save point, so you would need to go back before this chapter (or a new game) and check after that.

**Comment by kazuya-555** [comment]
"_and that version is what all later ports were based on_"

Those ae based on the Wii version, except the pre-UHD PC version and the Seperate Ways bonus game. Unless you`re saying they tweaked everything once ported, to be like the PS2 version and not simply the Novistador. Which would be weird if true...

**Comment by Mister-Curious** [comment]
> Unless you`re saying they tweaked everything once ported, to be like the PS2 version and not simply the Novistador.

I don't know much about what you speak of, and was simply quoting a comment from that YouTube video for context. Feel free to discuss any lore with that commenter.. Personally I don't care too much about what version had what. The port is a mess from top to bottom. I'm just grateful we have dedicated folks like Emoose and NipkowNix who are capable of remedying so much of the mess. 

The intention of my post here is to help the OP solve their issue, and perhaps lighten the load of endless issues that have come on this site (some of which are my own).

**Comment by HamilcarB** [comment]
> Here is a [download link ](https://drive.google.com/file/d/1Asw8ii9sSepajjGVI4Saz2p_G77h-tsh/view?usp=share_link)to the original emelon03.esl file for the vanilla RE4UHD. Try this one out and let me know if this resolves your issue. You will need to ensure you arent loading from a save because ESL data is stored there after each chapter end and save point, so you would need to go back before this chapter (or a new game) and check after that.

The issue has been resolved. Thank you.

**Comment by Mister-Curious** [comment]
> The issue has been resolved. Thank you.

Glad I could help. You should consider closing this issue considering how many there are still left open.

**Comment by HamilcarB** [comment]
> You should consider closing this issue considering how many there are still left open.

It is done.
