### ISSUE TITLE
"Assertion failed", can't run the game (cracked ver.)

### ISSUE THREAD

**Issue by BadTiger1** [nipkownix/re4_tweaks#60]
Well, when I pasted the “Bio32” folder into the game folder, I started up the game and then this happened:
https://scontent.fsgn2-4.fna.fbcdn.net/v/t1.15752-9/272603883_239074528381694_683445978681698889_n.png?_nc_cat=101&ccb=1-5&_nc_sid=ae9488&_nc_ohc=LVm7lj23MpIAX8DDOOI&_nc_ht=scontent.fsgn2-4.fna&oh=03_AVJ7pHfVUrjRrfjf98R4KEnkbceKBUJ-85pNoX6R5XTpAA&oe=622046B8.
My game version is a non-steam one so I really don’t know if that version can run the HD Project. And I also used the 4gb patch then it still gave the same result.

**Comment by emoose** [comment]
From the EXE size & the error msg my guess is wrong version of game, only 1.0.6 & 1.1.0 are supported by re4_tweaks, easiest way to get hold of those versions is to buy on Steam IMO, pretty sure there's a sale on right now too.

**Comment by nipkownix** [comment]
Yeah, what emoose said is probably the case.

Just in case someone else bumps into this post having the same issue with cracked versions:

Supporting those can be hard since we never know what modifications might have been done to the exe. That's without mentioning the fact that RE4 had about 7 different updates released on Steam, and we do our best to support the last two, which are the main versions still being distributed there.
There's no telling which one of these 7 versions is the one that was packaged in said cracked copy.

You can find the game for very cheap at various sites, so my advice is... buy the game. RE4 is pretty incredible (even if this port isn't the best it could be).

**Comment by emoose** [comment]
Looks like version number in bio4.exe properties can be used to tell game version btw:

* 1.0.0.0: v1.1.0
* 1.0.0RELEASE_DEV.0 - v1.0.6 debug
* 1.0.18384.1: v1.0.6
* 1.0.13328.1: v1.0.2
