### ISSUE TITLE
Feature Request: Turning off Mouse acceleration (if possible)

### ISSUE THREAD

**Issue by Zaphero1** [nipkownix/re4_tweaks#9]
Aside from adjusting sensitivity RE4 has two options for Mouse aiming "Classic", which gives you negative mouse acceleration, and "Modern", which gives you positive mouse acceleration and... yeah no option for no mouse acceleration. In fact changing that option just changes the value of MOUSE_ACC to 0 or 1 respectively. I don't know how feasible turning it off is; I hope the fact that there are two forms of mouse acceleration is helpful for finding where the value is applied so that it can be changed. Just listing this as an issue that's been bothering me (throws off my gyro aiming control setup) that I'm not sure is very visible or not.

**Comment by nipkownix** [comment]
Hmm, I've never actually noticed any positive mouse acceleration with the Modern setting, but I'll definitely take a look.

**Comment by nipkownix** [comment]
Well, I've been looking at this and I couldn't notice any mouse acceleration when using the "Modern" setting. Aiming in this game is kinda wonky still, since the camera and the gun's laser dot don't move in perfect sync, but the actual laser doesn't appear to have any acceleration.

@emoose, you play using KB/M, right? Did you notice any mouse accel?

**Comment by nipkownix** [comment]
While analyzing input for the `MouseTurning` feature, I concluded there really is no mouse acceleration when the game is using the "Modern" setting, so I'm closing this. 

Feel free to reopen the issue if you think I'm mistaken or that this can still be improved somehow.

**Comment by kailip7** [comment]
I'm not sure how you don't experience mouse acceleration with the Modern setting. I recorded a demonstration video of the very apparent (and aggressive) mouse acceleration present in the game using the Modern setting. I'm not sure if it's fixable but, if it is, it would be a massive improvement to the quality of life of playing the game.

https://www.youtube.com/watch?v=jEK6cf1CYy8

Both times I moved the mouse more slowly, the screen moved quite a bit less than with a faster movement, which made the character basically do a full 360 both times with the same distance covered by the mouse.

This example was recorded using Modern settings at 5 sensitivity ingame, my mouse is set to 1200 dpi.

**Comment by nipkownix** [comment]
Doesn't happen here for some reason.
Might be related to me using a low DPI with higher in-game sensitivity.

Guess I'll have to install my mouse's bloatware to raise the DPI and check again, lol

Thanks for the heads up.

**Comment by kailip7** [comment]
No problem, I really hope it's something that can somehow be fixed!

By the way, probably not relevant, but I also installed my mouse's bloatware in order to test with lower DPIs and higher sensitivity to see if the acceleration is less noticeable, and apparently my DPI is set to 1400, not 1200. My mistake.

I'm going to try with 400 dpi and somewhat higher sensitivity and I'll edit this comment later with my experience.

**Comment by nipkownix** [comment]
The game uses dinput to get mouse movements and calculate the delta speed, and some acceleration is probably being applied somewhere in there. Dinput is a mess though, so I'm hoping that PR #120 can solve this issue without having to deal with dinput at all.
